### ISSUE TITLE
utility scripts

### ISSUE THREAD

**Issue by AliGhaffarian** [sepsoh/awesome-bash-scripts#13]
wanted to implement "awesome-bash-scripts/Scripts/Internet Problem Fixer" and caught myself making utility functions one after another
asking for approval to modify install.sh to install utilities and add the Utilities directory

After the installations all utilities should be accessable via abs.utilities.name command

**Comment by sepsoh** [comment]
Hello, modularity is not considered at the moment.  Please make it a single file.Thanks
