### ISSUE TITLE
Script not writing to resolv.conf

### ISSUE THREAD

**Issue by alirezaalavi87** [sepsoh/awesome-bash-scripts#2]
OS: Arch Linux - LTS kernel

Hi.
So I run the command `sudo ~/Downloads/shecan.sh start` and the results are:
1- the `resolv.conf.shecan.bak` file gets created
2- the content of resolv.conf doesn't change:
```
# Generated by NetworkManager
search aps.lan
nameserver 192.168.127.18
nameserver 1.1.1.1
```

**Comment by alirezaalavi87** [comment]
the Issue seems to be raising from `sudo systemctl restart NetworkManager` , as it rewrites the contents of `resolv.conf`.
removed that line and it is working fine for now. that is of course before restarting NetworkManager.

**Comment by alirezaalavi87** [comment]
To fix this, I suggest using nmcli to update resolv.conf
OR, the changes will be overridden when networkManager restarts, but that has to be stated somwhere. so if we just don't restart network manager after starting the script it will be fine.

Also I think this is the same issue as in [this pull request](https://github.com/sepsoh/awesome-bash-scripts/pull/1)

**Comment by sepsoh** [comment]
thanks for your contributing I apply the changes.
